language: python
cache: pip
python:
  - 2.7
  - 3.6
install:
  - pip install flake8
  - npm install -g jshint
before_script:
  # stop the build if there are Python syntax errors, PEP8 violations, undefined names
  - flake8 . --count --select=E,F821,F822,F823 --max-line-length=127 --show-source --statistics
  # exit-zero treats all errors as warnings.  GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  - jshint .
script:
  - true  # add other tests here

matrix:
  include:
  ## linter for json files
    - language: node_js
      python:
      node_js:
        - 7
      install:
        - npm i -g eslint --save-dev
        - npm install eslint-plugin-json --save-dev -g
      before_script:
        - eslint --ext .json .
      script:
        - true

notifications:
  on_success: change
  on_failure: always
