language: python
cache: pip
python:
  - 2.7
  - 3.6
install:
  - pip install flake8
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  E111,E114 allow two space indentation.  GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --ignore=E111,E114  --max-complexity=10 --max-line-length=127 --statistics
script:
  - true  # add other tests here
notifications:
  on_success: change
  on_failure: always
