site_name: Fiware-DataModels
site_url: https://fiware-datamodels.readthedocs.org
repo_url: https://github.com/fiware/dataModels.git
site_description: FIWARE Data Models Documentation
docs_dir: .
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  -  Home: index.md
  -  Guidelines  : guidelines.md
  -  Alarms                      : 'Alarm/doc/introduction.md'
  -  Ambient:
      - 'AmbientObserved'        : 'AmbientObserved/doc/spec.md'
      - 'AirQualityThreshold'    : 'AirQualityThreshold/doc/spec.md'
  - Indicators:
      - 'KeyPerformanceIndicator' : 'KeyPerformanceIndicator/doc/spec.md'
  -  Parking:
      - 'Introduction'         : 'Parking/doc/introduction.md' 
      - 'OffStreetParking'     : 'Parking/OffStreetParking/doc/spec.md'
      - 'OffStreetParkingZone' : 'Parking/OffStreetParkingZone/doc/spec.md'
      - 'OnStreetParking'      : 'Parking/OnStreetParking/doc/spec.md'
      - 'ParkingAccess'        : 'Parking/ParkingAccess/doc/spec.md' 
      - 'ParkingSpot'          : 'Parking/ParkingSpot/doc/spec.md'
  -  'Parks & Gardens'         : 'ParksAndGardens/doc/introduction.md'          
  -  Points of interest: 
      - 'WeatherStation'       : 'PointOfInterest/WeatherStation/doc/spec.md'
      - 'AirQualityStation'    : 'PointOfInterest/AirQualityStation/doc/spec.md'
  -  'Issue Tracking'          : 'IssueTracking/doc/introduction.md'
  -  Device                    : 'Sensor/doc/introduction.md'
  -  'Street Lighting':
      - 'Introduction'         : 'StreetLighting/doc/introduction.md'
      - 'StreetLight'          : 'StreetLighting/StreetLight/doc/spec.md'      
  -  Weather:
      - 'WeatherObserved'      : 'Weather/WeatherObserved/doc/spec.md'
      - 'WeatherForecast'      : 'Weather/WeatherForecast/doc/spec.md'
      - 'WeatherAlarm'         : 'Weather/WeatherAlarm/doc/spec.md'
  -  'Waste Management':
      - 'Introduction'         : 'WasteManagement/doc/introduction.md'
      - 'WasteContainerIsle'   : 'WasteManagement/WasteContainerIsle/doc/spec.md'
      - 'WasteContainerModel'  : 'WasteManagement/WasteContainerModel/doc/spec.md'
      - 'WasteContainer'       : 'WasteManagement/WasteContainer/doc/spec.md'
  -  'Water Quality':
      - 'Introduction'         : 'WaterQuality/doc/introduction.md'
      - 'WaterQualityObserved' : 'WaterQuality/WaterQualityObserved/doc/spec.md'
